---
name: build

on:
  workflow_call:

env:
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  preflight:
    runs-on: ubuntu-latest
    outputs:
      terraform_version: ${{ steps.get_terraform_version.outputs.terraform_version }}
    steps:
      - uses: actions/checkout@v4

      - id: get_terraform_version
        name: Get Terraform version
        run: |
          set -euo pipefail

          terraform_version=$(cat ${GITHUB_WORKSPACE}/.tfswitchrc)
          echo "Terraform version: ${terraform_version}"
          echo "terraform_version=$terraform_version" >> "$GITHUB_OUTPUT"

  build:
    needs: preflight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ needs.preflight.outputs.terraform_version }}
          terraform_wrapper: false

      - name: Create Terraform plugin cache dir
        run: mkdir --parents $TF_PLUGIN_CACHE_DIR

      - id: cache-terraform-plugins
        name: Cache terraform plugins
        uses: actions/cache@v3
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: terraform-plugins-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install
        run: make install
        env:
          CI: true

      - name: Test
        run: make test
