---
name: CI

on:
  merge_group:
  pull_request:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  tag:
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Download vertag
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository_owner }}/vertag
          latest: true
          fileName: vertag_Linux_x86_64.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          extract: true

      - name: Run vertag
        env:
          BUILD_BOT_PAT: ${{ secrets.BUILD_BOT_PAT }}
        run: |
          ./vertag \
            --author-name "Build bot" \
            --author-email "build.bot@frontierhq.com" \
            --modules-dir "modules" \
            --remote-url "https://${BUILD_BOT_PAT}:x-oauth-basic@github.com/${{ github.repository_owner }}/azurerm-terraform-modules"
