---
name: Generate README

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install
        run: make install
        env:
          CI: true

      - name: Generate README
        run: make generate_readme branch=${GITHUB_REF##*/}

      - name: Commit, push and create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          body:
          branch: bot/update-readme
          commit-message: Update README [skip ci]
          title: Update README [skip ci]
          token: ${{ secrets.BUILD_BOT_PAT }}
